### ISSUE TITLE
API access

### ISSUE THREAD

**Issue by steveww** [instruqt/instruqt#20]
**Is your feature request related to a problem? Please describe.**
We would like API access to launch a specified topic/track and get a link back to the running instance.

**Describe the solution you'd like**
A REST API to:

- launch a specified instance
- get a status update on the instance readiness

**Describe alternatives you've considered**
NA

**Additional context**
For the purposes of using Instruqt to provide product demos. We would like to achieve this flow.

- User signs up with us for a demo
- Instance is launched
- A link to the running instance is emailed to the user

**Comment by steveww** [comment]
Additionally we would also need API access to get feedback for the track. E.g.
How long was it active, which challenges were completed.

**Comment by eveld** [comment]
is this not done?

**Comment by amochtar** [comment]
it is
