### ISSUE TITLE
CLI shouldn't require internet to work for commands that don't need internet

### ISSUE THREAD

**Issue by pvdissel** [instruqt/instruqt#22]
The `instruqt` command currently always needs internet, because it checks if there is an update of the CLI. Even when running `instruqt completion bash`...

The update check shouldn't fail if there is no internet, or if the update location cannot be reached, or if the update location is slow. It should just skip the update, without any error, making the instruqt command work as it should be. Specificly for commands don't need internet access to do their specific task.

**Comment by amochtar** [comment]
An `--update=false` flag has been added to the CLI. With this flag it will not perform the update check.
