### ISSUE TITLE
Firefox - Making application full screen overlays "challenge text" onto screen

### ISSUE THREAD

**Issue by brhahlen** [instruqt/instruqt#24]
**Describe the bug**
When in a challenge, and making the application full screen, the challenge text will overlay to the left side of the screen making it unable to interact with.

**To Reproduce**
In Firefox
1. Go to a challenge
2. Click on "full screen"
3. Text overlays to the left (in white, so hard to see)

**Expected behavior**
Text should disappear and not be overlayed.

**Screenshots**
![instruqt_overlay](https://user-images.githubusercontent.com/1798663/44718772-75689b80-aac1-11e8-9f74-7c5331082158.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 62

**Comment by eveld** [comment]
Fixed in next release
