### ISSUE TITLE
Code blocks grow outside of the assignment panel

### ISSUE THREAD

**Issue by eveld** [instruqt/instruqt#27]
**Describe the bug**
Code blocks in the assignment panel on the challenge screen are not nicely wrapped. It instead goes off-screen.

**To Reproduce**
1. Add a long command inside the challenge description.
2. Go to the challenge screen.
3. The command will flow outside of the assignment panel.

**Expected behavior**
That the command would nicely wrap and stay inside the bounds of the assignment panel.

**Comment by nielsvandoorn** [comment]
Hi Erik,

Will fix :+1:

**Comment by nielsvandoorn** [comment]
Hi Erik,

Should be fixed. Sorry for the delay.
