### ISSUE TITLE
Option to delete a track or topic

### ISSUE THREAD

**Issue by eveld** [instruqt/instruqt#32]
It would be nice if we could delete tracks and topics from the UI.

**Comment by nielsvandoorn** [comment]
Hi @eveld,

You can now delete tracks or topics using the web interface.

**For tracks:**
Go the the track page -> Click on "Metadata" to edit the track -> Scroll to the bottom of the page -> Click the "Delete this track" button

**For topics:**
Go to the topic page -> Click on "Edit topic" -> Scroll down to the bottom of the page -> Click the "Delete this topic" button
