### ISSUE TITLE
[ERROR] decoding response: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by koaning** [instruqt/instruqt#38]
**Describe the bug**

After running `instruqt track push` I keep hitting this error; 

```
==> Building track
    [ERROR] decoding response: invalid character '<' looking for beginning of value
```

I've seen it 3 times this week. 

**To Reproduce**

This is hard. 

**Expected behavior**

No error. 

**Desktop (please complete the following information):**
- MacOS X 

@amochtar is aware of this behavior

**Comment by koaning** [comment]
The error does go away after waiting and doing a retry. Just a though, the CLI could also attempt this retry.

**Comment by amochtar** [comment]
I've pushed a fix for this, which should prevent this from happening. As it's not easy to reproduce, I'm not 100% sure that it is fixed. Could you keep an eye on this?

**Comment by koaning** [comment]
Yes. I'll close the issue for now since I've not seen it appear today. Should it come back I'll pick it up once again here.
